package vut.gui;

import java.text.NumberFormat;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import vut.data.EmployeeClass;
import vut.data.EmployeeClass.EmployeeType;
import vut.data.HourlyEmployeeClass;
import vut.data.ManagerClass;
import vut.data.SalariedEmployeeClass;

/**
 *
 * @author
 */
public class EmployeeDataEntry extends javax.swing.JFrame {

    public static ArrayList<HourlyEmployeeClass> arrLstHourlyEmp = new ArrayList();
    public static ArrayList<SalariedEmployeeClass> arrLstSalariedEmp = new ArrayList();
    public static ArrayList<ManagerClass> arrLstManager = new ArrayList();
   

    /**
     * Creates new form EmlpyeeDataEntry
     */
    public EmployeeDataEntry() {
        initComponents();
        radioGroup();
        hideEmployeePanel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        radSalariedEmployee = new javax.swing.JRadioButton();
        radHourlyEmployee = new javax.swing.JRadioButton();
        radManager = new javax.swing.JRadioButton();
        pnlSalariedEmployee = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtAnnualSalary = new javax.swing.JTextField();
        pnlHourlyEmployee = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtHourlyWage = new javax.swing.JTextField();
        pnlManager = new javax.swing.JPanel();
        txtWeeklyBonus = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnCreateEmployee = new javax.swing.JButton();
        btnClaculateSalaries = new javax.swing.JButton();
        pnlViewEmployees = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taEmployees = new javax.swing.JTextArea();
        btnViewSalariedEmployees = new javax.swing.JButton();
        btnViewHourlyEmployees = new javax.swing.JButton();
        btnViewManagers = new javax.swing.JButton();
        btnVewEmployees = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Data Entry Form");

        jLabel1.setText("Employee ID");

        jLabel2.setText("Employee name:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(24, 24, 24)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(49, 49, 49)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Employee Type"));

        radSalariedEmployee.setText("Salaried Employee");
        radSalariedEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radSalariedEmployeeActionPerformed(evt);
            }
        });

        radHourlyEmployee.setText("Hourly Employee");
        radHourlyEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radHourlyEmployeeActionPerformed(evt);
            }
        });

        radManager.setText("Manager");
        radManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radManagerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radSalariedEmployee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radHourlyEmployee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radManager)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radSalariedEmployee)
                    .addComponent(radHourlyEmployee)
                    .addComponent(radManager))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pnlSalariedEmployee.setBorder(javax.swing.BorderFactory.createTitledBorder("Salaried Employee"));

        jLabel4.setText("Annual salary");

        txtAnnualSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnnualSalaryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSalariedEmployeeLayout = new javax.swing.GroupLayout(pnlSalariedEmployee);
        pnlSalariedEmployee.setLayout(pnlSalariedEmployeeLayout);
        pnlSalariedEmployeeLayout.setHorizontalGroup(
            pnlSalariedEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSalariedEmployeeLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAnnualSalary, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        pnlSalariedEmployeeLayout.setVerticalGroup(
            pnlSalariedEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSalariedEmployeeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlSalariedEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAnnualSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlHourlyEmployee.setBorder(javax.swing.BorderFactory.createTitledBorder("Hourly Employee"));

        jLabel5.setText("Hourly wage");

        txtHourlyWage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHourlyWageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlHourlyEmployeeLayout = new javax.swing.GroupLayout(pnlHourlyEmployee);
        pnlHourlyEmployee.setLayout(pnlHourlyEmployeeLayout);
        pnlHourlyEmployeeLayout.setHorizontalGroup(
            pnlHourlyEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHourlyEmployeeLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtHourlyWage, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );
        pnlHourlyEmployeeLayout.setVerticalGroup(
            pnlHourlyEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHourlyEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHourlyEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtHourlyWage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlManager.setBorder(javax.swing.BorderFactory.createTitledBorder("Manager"));

        txtWeeklyBonus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWeeklyBonusActionPerformed(evt);
            }
        });

        jLabel6.setText("Weekly bonus");

        javax.swing.GroupLayout pnlManagerLayout = new javax.swing.GroupLayout(pnlManager);
        pnlManager.setLayout(pnlManagerLayout);
        pnlManagerLayout.setHorizontalGroup(
            pnlManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlManagerLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtWeeklyBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlManagerLayout.setVerticalGroup(
            pnlManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlManagerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWeeklyBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap())
        );

        btnCreateEmployee.setText("Create Employee ");
        btnCreateEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateEmployeeActionPerformed(evt);
            }
        });

        btnClaculateSalaries.setText("Calculate Salaries");
        btnClaculateSalaries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClaculateSalariesActionPerformed(evt);
            }
        });

        pnlViewEmployees.setBorder(javax.swing.BorderFactory.createTitledBorder("View Employees"));

        taEmployees.setColumns(20);
        taEmployees.setRows(5);
        jScrollPane1.setViewportView(taEmployees);

        btnViewSalariedEmployees.setText("View Salaried Employees");
        btnViewSalariedEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSalariedEmployeesActionPerformed(evt);
            }
        });

        btnViewHourlyEmployees.setText("View Hourly Employees");
        btnViewHourlyEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewHourlyEmployeesActionPerformed(evt);
            }
        });

        btnViewManagers.setText("View Managers");
        btnViewManagers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewManagersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlViewEmployeesLayout = new javax.swing.GroupLayout(pnlViewEmployees);
        pnlViewEmployees.setLayout(pnlViewEmployeesLayout);
        pnlViewEmployeesLayout.setHorizontalGroup(
            pnlViewEmployeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewEmployeesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlViewEmployeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnViewSalariedEmployees, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewHourlyEmployees, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewManagers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlViewEmployeesLayout.setVerticalGroup(
            pnlViewEmployeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewEmployeesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnViewSalariedEmployees)
                .addGap(18, 18, 18)
                .addComponent(btnViewHourlyEmployees)
                .addGap(18, 18, 18)
                .addComponent(btnViewManagers)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlViewEmployeesLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnVewEmployees.setText("View Employees");
        btnVewEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVewEmployeesActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 102, 102));
        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlSalariedEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlHourlyEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pnlViewEmployees, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCreateEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btnVewEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(208, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnClaculateSalaries, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlHourlyEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlSalariedEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClaculateSalaries, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVewEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(pnlViewEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAnnualSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnnualSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnnualSalaryActionPerformed

    private void txtHourlyWageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHourlyWageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHourlyWageActionPerformed

    private void txtWeeklyBonusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWeeklyBonusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWeeklyBonusActionPerformed

    private void btnCreateEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateEmployeeActionPerformed
        NumberFormat currFormat = NumberFormat.getCurrencyInstance();

        if (!txtID.getText().isEmpty() || !txtName.getText().isEmpty()) {
            try {
                if (radSalariedEmployee.isSelected()) {
                    SalariedEmployeeClass objSalariedEmp = new SalariedEmployeeClass(txtID.getText(), txtName.getText(), EmployeeType.SALARIED, Double.parseDouble(txtAnnualSalary.getText()));

                    arrLstSalariedEmp.add(objSalariedEmp);
                    clear();
                } else if (radHourlyEmployee.isSelected()) {
                    HourlyEmployeeClass objHourlyEmp = new HourlyEmployeeClass(txtID.getText(), txtName.getText(), EmployeeType.HOURLY, Double.parseDouble(txtHourlyWage.getText()));

                    arrLstHourlyEmp.add(objHourlyEmp);
                    clear();
                } else if (radManager.isSelected()) {
                    ManagerClass objManager = new ManagerClass(txtID.getText(), txtName.getText(), EmployeeType.MANAGER, Double.parseDouble(txtAnnualSalary.getText()), Double.parseDouble(txtWeeklyBonus.getText()));

                    arrLstManager.add(objManager);
                    clear();
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            } catch (IllegalArgumentException e) {
                JOptionPane.showMessageDialog(this, "Error" + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Name and/or ID Text Fields are Empty", "Input Invalid", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_btnCreateEmployeeActionPerformed

    private void radSalariedEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radSalariedEmployeeActionPerformed
        pnlSalariedEmployee.setVisible(true);
        pnlHourlyEmployee.setVisible(false);
        pnlManager.setVisible(false);
    }//GEN-LAST:event_radSalariedEmployeeActionPerformed

    private void radHourlyEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radHourlyEmployeeActionPerformed
        pnlHourlyEmployee.setVisible(true);
        pnlManager.setVisible(false);
        pnlSalariedEmployee.setVisible(false);
    }//GEN-LAST:event_radHourlyEmployeeActionPerformed

    private void radManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radManagerActionPerformed
        pnlManager.setVisible(true);
        pnlSalariedEmployee.setVisible(true);
        pnlHourlyEmployee.setVisible(false);
    }//GEN-LAST:event_radManagerActionPerformed

    private void btnClaculateSalariesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClaculateSalariesActionPerformed
        EmployeeDataManipulationForm empData = new EmployeeDataManipulationForm();
        empData.setVisible(true);
    }//GEN-LAST:event_btnClaculateSalariesActionPerformed

    private void btnVewEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVewEmployeesActionPerformed
        pnlViewEmployees.setVisible(true);
    }//GEN-LAST:event_btnVewEmployeesActionPerformed

    private void btnViewSalariedEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSalariedEmployeesActionPerformed
        taEmployees.setText("");
        for (int i = 0; i < arrLstSalariedEmp.size(); i++) {
            //if (arrLstSalariedEmp.get(i).getEmployeeType().equals(EmployeeType.SALARIED)) {
            taEmployees.append(arrLstSalariedEmp.get(i).toString());

            //}
        }

    }//GEN-LAST:event_btnViewSalariedEmployeesActionPerformed

    private void btnViewHourlyEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewHourlyEmployeesActionPerformed
        taEmployees.setText("");
        for (int i = 0; i < arrLstHourlyEmp.size(); i++) {
            //if (arrLstHourlyEmp.get(i).getEmployeeType().equals(EmployeeType.HOURLY)) {
            taEmployees.append(arrLstHourlyEmp.get(i).toString());

            //}
        }
    }//GEN-LAST:event_btnViewHourlyEmployeesActionPerformed

    private void btnViewManagersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewManagersActionPerformed
        taEmployees.setText("");
        for (int i = 0; i < arrLstManager.size(); i++) {
            //if (arrLstManager.get(i).getEmployeeType().equals(EmployeeType.MANAGER)) {
            taEmployees.append(arrLstManager.get(i).toString());

            //}
        }
    }//GEN-LAST:event_btnViewManagersActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void hideEmployeePanel() {
        pnlHourlyEmployee.setVisible(false);
        pnlManager.setVisible(false);
        pnlSalariedEmployee.setVisible(false);
        pnlViewEmployees.setVisible(false);
    }

    private void radioGroup() {

        ButtonGroup radGrp = new ButtonGroup();
        radGrp.add(radHourlyEmployee);
        radGrp.add(radManager);
        radGrp.add(radSalariedEmployee);
    }

    private void clear() {
        hideEmployeePanel();
        pnlViewEmployees.setVisible(false);
        txtAnnualSalary.setText("");
        txtHourlyWage.setText("");
        txtID.setText("");
        txtName.setText("");
        txtWeeklyBonus.setText("");
        radSalariedEmployee.setSelected(false);
        radHourlyEmployee.setSelected(false);
        radManager.setSelected(false);
        taEmployees.setText("");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeDataEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeDataEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeDataEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeDataEntry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeDataEntry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClaculateSalaries;
    private javax.swing.JButton btnCreateEmployee;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnVewEmployees;
    private javax.swing.JButton btnViewHourlyEmployees;
    private javax.swing.JButton btnViewManagers;
    private javax.swing.JButton btnViewSalariedEmployees;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlHourlyEmployee;
    private javax.swing.JPanel pnlManager;
    private javax.swing.JPanel pnlSalariedEmployee;
    private javax.swing.JPanel pnlViewEmployees;
    private javax.swing.JRadioButton radHourlyEmployee;
    private javax.swing.JRadioButton radManager;
    private javax.swing.JRadioButton radSalariedEmployee;
    private javax.swing.JTextArea taEmployees;
    private javax.swing.JTextField txtAnnualSalary;
    private javax.swing.JTextField txtHourlyWage;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtWeeklyBonus;
    // End of variables declaration//GEN-END:variables
}
