package vut.gui;

import java.text.NumberFormat;
import javax.swing.JOptionPane;
import vut.data.HourlyEmployeeClass;
import vut.data.ManagerClass;
import vut.data.SalariedEmployeeClass;
import static vut.gui.EmployeeDataEntry.arrLstHourlyEmp;

/**
 *
 * @author Mrs S Moyo
 */
public class EmployeeDataManipulationForm extends javax.swing.JFrame {
    
    NumberFormat currFormat = NumberFormat.getCurrencyInstance();

    /**
     * Creates new form EmployeeDataManipulationForm
     */
    public EmployeeDataManipulationForm() {
        initComponents();
        populateCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl = new javax.swing.JPanel();
        cmboIdNo = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDisplayData = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Data Manipulation Form (your student number)");

        cmboIdNo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select IDNumber:" }));
        cmboIdNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmboIdNoActionPerformed(evt);
            }
        });

        taDisplayData.setEditable(false);
        taDisplayData.setColumns(20);
        taDisplayData.setRows(5);
        taDisplayData.setName(""); // NOI18N
        jScrollPane1.setViewportView(taDisplayData);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jButton1.setText("close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLayout = new javax.swing.GroupLayout(pnl);
        pnl.setLayout(pnlLayout);
        pnlLayout.setHorizontalGroup(
            pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLayout.createSequentialGroup()
                .addComponent(cmboIdNo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlLayout.setVerticalGroup(
            pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmboIdNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmboIdNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmboIdNoActionPerformed

        final int MAX_HOURS = 40;
        String idNo = cmboIdNo.getSelectedItem().toString();

        for (int i = 0; i < EmployeeDataEntry.arrLstHourlyEmp.size(); i++) {
            if (EmployeeDataEntry.arrLstHourlyEmp.get(i).getIdNumber().equals(idNo)) {

                HourlyEmployeeClass hourlyEmpObj = EmployeeDataEntry.arrLstHourlyEmp.get(i);
                int hoursWorked = Integer.parseInt(JOptionPane.showInputDialog("Enter hours worked by the employee"));
                taDisplayData.setText(hourlyEmpObj.toString() + "\nPay:\t" + currFormat.format(hourlyEmpObj.weeklyPay(hoursWorked)) + "\n");
            }
        }
        for (int i = 0; i < EmployeeDataEntry.arrLstSalariedEmp.size(); i++) {
            if (EmployeeDataEntry.arrLstSalariedEmp.get(i).getIdNumber().equals(idNo)) {
                SalariedEmployeeClass salariedEmpObj = EmployeeDataEntry.arrLstSalariedEmp.get(i);
                taDisplayData.setText(salariedEmpObj.toString() + "\nPay:\t" + currFormat.format(salariedEmpObj.weeklyPay(MAX_HOURS)) + "\n");
            }
        }
        for (int i = 0; i < EmployeeDataEntry.arrLstManager.size(); i++) {
            if (EmployeeDataEntry.arrLstManager.get(i).getIdNumber().equals(idNo)) {
                ManagerClass managerObj = EmployeeDataEntry.arrLstManager.get(i);

                taDisplayData.setText(managerObj.toString() + "\nPay:\t" + currFormat.format(managerObj.weeklyPay(MAX_HOURS)) + "\n");
            }

        }


    }//GEN-LAST:event_cmboIdNoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void populateCombo() {

        cmboIdNo.removeAll();

        for (int i = 0; i < arrLstHourlyEmp.size(); i++) {

            cmboIdNo.addItem(EmployeeDataEntry.arrLstHourlyEmp.get(i).getIdNumber() + "");

        }
        for (int i = 0; i < EmployeeDataEntry.arrLstSalariedEmp.size(); i++) {

            cmboIdNo.addItem(EmployeeDataEntry.arrLstSalariedEmp.get(i).getIdNumber() + "");

        }
        for (int i = 0; i < EmployeeDataEntry.arrLstManager.size(); i++) {

            cmboIdNo.addItem(EmployeeDataEntry.arrLstManager.get(i).getIdNumber() + "");

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeDataManipulationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeDataManipulationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeDataManipulationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeDataManipulationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeDataManipulationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmboIdNo;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnl;
    private javax.swing.JTextArea taDisplayData;
    // End of variables declaration//GEN-END:variables
}
